version: '3'
services: 
 #base de datos
  database:
    image: mysql:latest
    container_name: database-incidents
    command: mysqld --character-set-filesystem=utf8 --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --default-authentication-plugin=mysql_native_password 
    restart: always
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: incident_log
      MYSQL_USER: esolart
      MYSQL_PASSWORD: esolart123csa
    ports: 
      - 3306:3306
    volumes: 
      - ./database/:/docker-entrypoint-initdb.d/
    networks: 
      - esnet

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - database
    ports: 
      - 8080:8080
    networks: 
      - esnet

networks: 
  esnet: 
    driver: bridge

