DROP TABLE IF EXISTS incident_log;
CREATE TABLE incident_log (
    incident_log_id INT NOT NULL AUTO_INCREMENT,
    fk_product_id INT NOT NULL,
    inl_IM VARCHAR (50) NOT NULL,
    inl_description TEXT,
    escalation_date DATE NOT NULL,
    scaled_to VARCHAR (100) NOT NULL,
    inl_status TINYINT (2) NOT NULL,
    closing_date DATE,
    inl_comments TEXT,
    user_processed VARCHAR (80),
    PRIMARY KEY(incident_log_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE incident_log ADD CONSTRAINT fk_products_id FOREIGN KEY (fk_product_id) REFERENCES products(product_id) ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO incident_log VALUES 

(NULL,2, 'IM-13168', '"Intentar hacer el retiro por la página del Banco, el pr21eso llega hasta cuán8 debe darle acepta. RR"', '2018-07-27', 'juan Pablo Ospino ', 2, '2019-03-22', 'Me 23rmito informar que se dará cierre al número de incidente IM-13168 debi8 a que no se obtuvo retroalimentación por parte de laboratorio digital (ADL) res23cto al error presenta8 por el cliente al momento de realizar sus transferencias como se evidencia en el histórico de correo, el cierre se realiza debi8 a que ATH no tiene el soporte a nivel de desarrollo para PB Banco de Bogotá.',NULL),
(NULL,2, 'IM-19517', 'Cliente manifiesta error al consultar detalles de las trasferencias realizadas y se presenta el error de la pantalla 2.', '2018-08-10', 'juan Pablo Ospino ', 2, '2019-03-29', 'rta ath: Me 23rmito informar que se dará cierre al número de incidente IM-19517  debi8 a que no se obtuvo retroalimentación por parte de laboratorio digital (ADL) res23cto al error presenta8 por el cliente al momento de consultar el detalle de las transferencias como se evidencia en el histórico de correo, el cierre se realiza debi8 a que ATH no tiene el soporte a nivel de desarrollo para PB Banco de Bogotá',NULL),
(NULL,2, 'IM2204744', 'Cliente hizo utilización de 20 millones de su crediservice y cuan8 quiso diferirlo a 48 cuotas el PB solo des11iega 36. CONSULTA', '2018-11-13', 'juan Pablo Ospino ', 2, '2019-01-28', 'Juan Pablo Ospino indica el producto crediservice únicamente puede ser diferi8 a 36. por favor validar con el área de neg21io si es posible hacerlo a 48 cuotas ya que es una definición de neg21io.',NULL),
(NULL,2, 'IM-24128', 'Cliente intenta hacer inversión a la fiducia y se genera error.', '2018-11-20', 'juan Pablo Ospino ', 2, '2019-01-29', '"Correo recibio el dia martes 29 de enero a las 4:21 pm  El cliente ya puede hacer inversión y desinversión en la fiducia, para el  time timeOut  se tiene el siguiente seguimiento el cual se está validan8 por parte de la fiducia, estos casos son esporádicos:"',NULL),
(NULL,2, 'IM-24565', 'Cliente intenta actualizar dire6ión de residencia y se genera el siguiente error:  “En este momento no es posible realizar la consulta de dire6iones de envió de correspondencia..”.', '2018-11-23', 'juan Pablo Ospino ', 2, '2019-03-26', '"rta ath: Nos encontramos 23ndientes aún de la definición. para soporte, no se recibe respuesta de ADL"',NULL),
(NULL,2, 'IM-27067', 'La sesión del usuario no está caducan8 y continua activa. ', '2018-12-10', 'juan Pablo Ospino ', 2, '2019-03-26', '"rta ath: Nos encontramos 23ndientes aún de la definición. para soporte, no se recibe respuesta de ADL"',NULL),
(NULL,2, 'IM-14624', '"NO SE MUESTRA INFORMACION DE TODAS LAS OBLIGACIONES DEL CLIENTE A 23SAR DE QUE EL BANCO LAS ENVÍA,  SE ESCALA A LABORATORIO DIGITAL EL 11 DE SEPTIEMBRE"', '2018-08-02', 'juan Pablo Ospino ', 2, '2019-03-26', '"rta ath: Nos encontramos 23ndientes aún de la definición. para soporte, no se recibe respuesta de ADL"',NULL),
(NULL,2, 'IM-26460', '"NO SE MUESTRA INFORMACION DE LA TARJETA DEBITO DEL USUARIO PARA OPCIONES DE SEGURIDAD, SE ESCALA A LABORATORIO DIGITAL YA QUE LA INFORMACION SI ES ENVIADA POR EL BANCO 23RO LABORATORIO NO HA RESPONDIDO, SE ESCALA A LABORATORIO EL 4 DE DICIEMBRE"', '2018-11-16', 'juan Pablo Ospino ', 2, '2019-03-26', '"rta ath: Nos encontramos 23ndientes aún de la definición. para soporte, no se recibe respuesta de ADL"',NULL),
(NULL,2, 'IM-31340 IM-30347 ', 'RV: URGENTE PREMIUM  Transferencias Sra Ruby Rodríguez 6 51832989', '2019-01-03', 'juan Pablo Ospino ', 2, '2018-12-28', '"Respuesta de Derly Huertas: Se valida la cuenta corriente del cliente No. 062737531 y no se evidencia rechazos para las fechas y montos menciona8s sin embargo se valida lo siguiente: Rechazo día 27/12-2018 por concepto - SOBREPASA LIMITE PAGO CUENTA NACIONAL 278, el monto que intentaba transferir el cliente fue por un valor de $ 16.000.000, favor validar el límite de cuenta nacional del cliente. Transación exitosa el día 28-12-2018 - Transferencia al Banco O6idente a la cta cte # 256063074 por Internet el 28/12/2018, el monto de transa6ión fue por $ 50.000  No se observan transa6iones con rechazo para la fecha 28-12-2018 y tamp21o por valor de $ 2.165.000.  Favor validar con el cliente si a la fecha sigue presentan8 la inconciencia."',NULL),
(NULL,2, '135528914', 'Servicios Publicos no disponible para pagos Acueducto - Movistar', '2018-12-11', 'juan Pablo Ospino ',2, '2019-01-28', 'Este caso fue resuelto en su momento y se habló con el comercial para que le solicitara gestionar PORTAL EMPRESARIAL.Servicios Públicos no disponible para pagos Acueducto - Movistar --> Movistar hizo cambios de los número de referencia es necesario validar que el número al que se está pagan8 sea el nuevo número',NULL),
(NULL,2, 'IM-27464', '"Cliente JACKELINE SAAVEDRA 6 38.612.946 quien nuevamente se le genera error en su portal de 23rsona natural, 8nde no visualiza las cuentas ya inscritas, además que le genera error para cualquier transa6ión las cuales vienen realizan8 de13e hace mas de 8s años, se reviso sus cuentas confirman8 to23s y demás"', '2018-12-06', 'juan Pablo Ospino ',2, '2019-01-28', 'Juan Pablo Ospino reporta Este caso fue resuelto en su momento y se habló con el comercial para que le solicitara gestionar PORTAL EMPRESARIAL.',NULL),
(NULL,2, 'IM-26460', '"Cambio Seguridad tarjeta Debito, PROBLEMAS EN LA PAGINA EXP 11626039  JUAN MARTINEZ 6 1019059152 DERIVA8 11656575"', '2018-12-04', 'juan Pablo Ospino ',2, '2019-03-26', '"rta ath: Nos encontramos 23ndientes aún de la definición. para soporte, no se recibe respuesta de ADL"',NULL),
(NULL,15, '', '"Error al realizar activacion 15 por cualquier medio, corresponde a error de as21iacion en pr21eso de 15, en este caso los clientes no pueden realizar activacionde su 15"', '2018-11-30', '"equipo 15 scrum, PO"',2, '2019-02-15', '"Se recibio el dia de hoy 15 /02/2019 la confirmacion por parte del PO de tarjetas de credito digital, que el incidente de as21iacion que causaba problemas en la activacion de las tarjetas ha si8 soluciona8, por lo que los clientes pueden pr21eder con la activacion de las mismas"',NULL),
(NULL,15, '', '"Solicito de su amable colaboración indican8 la 15 que se debe enviar, ya que el día 17/01/2019 se presento du11icidad en un producto lab digital y es necesario identificar la 15 correcta a enviar."', '2019-01-18', '"scrum, PO"',2, '2019-01-23', '"Buenas tardes, por favor realzar la terminada en 6526, gracias. Att Luis guillermo n"',NULL),
(NULL,15, '', 'Error al obtener el logo del participante', '2019-01-21', '"scrum, PO, desarrolla8r"',2, '2019-06-01', '', NULL),
(NULL,14, '"IM1663495 /// IM1774727"', 'error en creación exención 4x100 y desbloqueo TD por lo cual se reporta la siguiente novedad con el número de incidente masivo IM1663495', '2019-01-18', 'scrum PO',2, '2019-05-20', '"se valida con equipo de cuentas digitales, inconveniente 4 x mil corregi8 14-03-2019 //// 23ndiente desbloqueo td  20-05-2019, el equipo de oficina digital nos confirma por correo que este tema fue instala8 en produ6ión por otro equipo 23ro nunca ha funciona8 correctamente y se pr21edera a eliminar la opción del facilita8r de servicios de forma prioritaria y posteriormente se definirá por el PO del equipo la inclusión del mismo"',NULL),
(NULL,1, '', 'cliente jorge muñoz presenta inconvnientes para ingreso a banca movil', '2018-11-17', '"scrum, PO"',2, '2019-05-20', '"20-05-2019, Para el caso de Jorge Muñoz se ha envia8 evidencia en re23tidas 21asiones al área de Gestión de Incidentes, con el error que devuelve el servicio al canal (Adjunto último correo). El tema fue escala8 a Dire6ión de Desarrollo aún sin respuesta.  20-05-2019 18:00:00, por medio de correo electronico gestion de incidentes confirma que : ""se actualizo producto por producto y por último la fiducia, una vez se actualizo en la fiducia',NULL),
(NULL,1, '', 'error pago servicion publicos electricaribe', '2018-09-20', '"scrum, PO"', '2', '2019-02-20', '"Se Confirma con Randy quien reporto el incidente, que con la instalacion de la ultima version 9.0.12 el pago de servicios AAA ya funcionan exitosamente"', NULL),
(NULL,6, 'IM1665337 ', 'Falla en solicitudes de credito de consumo se presenta intermitencia en flujo de aprobacion', '2019-01-22', 'DevOps y Scrum',2, '2019-01-30', '"Se des11ego en produ6ión un nuevo desarrollo que busca mitigar el error presenta8, por lo cual, agradezco brindar la instru6ión a los comerciales de que pueden volver a intentar el pr21eso."', NULL),
(NULL,15, '', '"Solicitamos de su apoyo, pues nos llega un nuevo reporte de un cliente 6 1117542359, que no puede radicar la solicitud de 15, le genera el error OWNING BRANCH NOT ON FILE, el mismo error se identifica en logs en diferentes días que el cliente ha intenta8 hacer la solicitud Se valida y el código de la oficina que queda registra8 es: 9281, la cual no existe"', '2019-01-14', '"scrum, PO, desarrolla8r"',2,NULL,NULL,NULL),
(NULL,7, 'IM1655026 - IM1670308 IM1681822', '"Error en activacion de TD, en o23ncard las tarjetas aparecen as21iadas a otras personas, IM1655026 - IM1670308 "', '2019-01-10', '"scrum, PO, desarrollador"',2, '2019-02-12', '"incidente se escalo con gestion de incidentes, quienes solicitan validar la orquestacion del servicio',NULL),
(NULL,1, 'IM1674282', '"NO HAY INGRESO AL SERVICIOS BANCA MÓVIL, SE QUEDA PR21ESAN8 DATOS DE LOGUIN  30/01/19 18:07:07 AMERICA/BOGOTA (HROJAS2): MIÉRCOLES 30/01/2019 5:45 P.M. ==> SE EFECTUA  VALIDACION EN LOGS DE WEBLOGIC Y NO LLEGA LAS SOLICITUDES DE CONEXION MIÉRCOLES 30/01/2019 5:56 P.M. ==> SE HABLA CON ANGELA DE LAB DIGITAL, QUIEN INFORMA QUE ES UN BUG EN LA A11ICACION Y QUE YA ESTAN REVISAN8."', '2019-01-30', '"PO"',2, '2019-01-31', '"se valida con equipo banca movil, ya se encuentra funcionan8"', NULL),
(NULL,15, '', '"Falla en solicitud de 15 por Cost Report, cuanDO va a actualizar datos en CRM, si el valor de cost report es 0, la solicitud es fallida"', '2019-02-04', '"scrum, PO, desarrolla8r"',2, '2019-02-06', 'PO de 15 nos confirma que se des11ego la solucion de esta falla el dia 6 de febrero',NULL),
(NULL,7, 'IM1688457 ', '"Error en creación de cuenta de ahorros, Departamento de Lugar de Nacimiento es un campo requeri8, se sigue presentan8 con frecuencia, hoy 26-03-2019 se presentan 5 casos"', '2019-01-04', '"scrum, PO, desarrolla8r"',2, '2019-08-02', '"05-08-2019 SE RECIBE CONFIRMACION DEL GRUPO DE DESARROLLO QUE SE IM11EMENTO EL FIX A LA SOLUCION DE ESTA NOVEDAD',NULL),
(NULL,6, '', 'Solicitudes paralelas no estan mostran8 rechazo en credito de consumo digital', '2019-02-05', '"scrum, PO, desarrolla8r"',2, '2019-02-20', '"PO reporta que el servicio de consultas de paralelas, ods y datacredito estan bien, el unico incidente encontra8 es que la pantalla mostrada al cliente no concuerda con el flujo, pues a 23sar de rechazar por una solicitud paralela',NULL),
(NULL,7, '2585', 'Error al notificar canal de venta en CRM', '2019-02-05', '"Scrum, PO, DevOps"', 2, '2019-04-05', '"PO nos confirma, Este ajuste ya lo realizamos y está confirma8 por el equipo de Consumo en el cuál las cuentas están crean8 creadas en el canal correspondiente (tener en cuenta que en CRM se evidencia un día después)"',NULL);

